---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: pagekit
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-pass
type: Opaque
stringData:
  password: ninguna
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pagekit-mysql
  labels:
    app: pagekit
spec:
  selector:
    matchLabels:
      app: pagekit
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: pagekit
        tier: mysql
    spec:
      containers:
        - image: kubesail/mysql:5.6
          imagePullPolicy: Always
          name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  # Import our mysql-pass.password
                  # as MYSQL_ROOT_PASSWORD
                  name: mysql-pass
                  key: password
            - name: MYSQL_DATABASE
              value: pagekit
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            # Mount our PersistentVolumeClaim
            # to /var/lib/mysql
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
          resources:
            requests:
              cpu: 5m
              memory: 128Mi
            limits:
              cpu: 100m
              memory: 128Mi
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: pagekit-mysql
  labels:
    app: pagekit
spec:
  ports:
    - port: 3306
  selector:
    # Note that these match the "labels" in MySQL
    app: pagekit
    tier: mysql