apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: pagekit
  name: pagekit
spec:
  selector:
    matchLabels:
      app: pagekit
      tier: frontend
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: pagekit
        tier: frontend
    spec:
      containers:
      - image: quoaum/pagekit:latest
        name: pagekit-frontend
        #command: ["/usr/bin/pagekit"]
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 15m
            memory: 384Mi
          limits:
            cpu: 900m
            memory: 384Mi
      restartPolicy: Always